/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author nicol
 */
public class vistaRegistroServiciosAdicionales extends javax.swing.JFrame {

    /**
     * Creates new form vistaRegistroServiciosAdicionales
     */
    public vistaRegistroServiciosAdicionales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        checkboxGimnasio = new javax.swing.JCheckBox();
        checkboxPiscina = new javax.swing.JCheckBox();
        checkboxSpa = new javax.swing.JCheckBox();
        checkboxNinguno = new javax.swing.JCheckBox();
        botonElegirServiciosAdicionales = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        labelCostoTotalAdicionales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(227, 242, 193));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servicios Adicionales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel37.setText("<html>Selecciona algún servicio adicional que quieras adquirir. Si no es el caso, selecciona la casilla ''Ninguno'' y confirma<html>");

        checkboxGimnasio.setBackground(new java.awt.Color(227, 242, 193));
        checkboxGimnasio.setText("Gimnasio - $240.000");
        checkboxGimnasio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxGimnasioActionPerformed(evt);
            }
        });

        checkboxPiscina.setBackground(new java.awt.Color(227, 242, 193));
        checkboxPiscina.setText("Piscina - $65.000");

        checkboxSpa.setBackground(new java.awt.Color(227, 242, 193));
        checkboxSpa.setText("Spa - $310.000");
        checkboxSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxSpaActionPerformed(evt);
            }
        });

        checkboxNinguno.setBackground(new java.awt.Color(227, 242, 193));
        checkboxNinguno.setText("Ninguno");
        checkboxNinguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxNingunoActionPerformed(evt);
            }
        });

        botonElegirServiciosAdicionales.setText("Seleccionar");

        jLabel38.setText("Total: $");

        labelCostoTotalAdicionales.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCostoTotalAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonElegirServiciosAdicionales))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(checkboxSpa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkboxPiscina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkboxGimnasio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(checkboxNinguno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkboxGimnasio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxPiscina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxSpa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkboxNinguno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCostoTotalAdicionales)
                    .addComponent(botonElegirServiciosAdicionales)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxGimnasioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxGimnasioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxGimnasioActionPerformed

    private void checkboxSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxSpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxSpaActionPerformed

    private void checkboxNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxNingunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxNingunoActionPerformed

    public JButton getBotonElegirServiciosAdicionales() {
        return botonElegirServiciosAdicionales;
    }

    public JCheckBox getCheckboxGimnasio() {
        return checkboxGimnasio;
    }

    public JCheckBox getCheckboxNinguno() {
        return checkboxNinguno;
    }

    public JCheckBox getCheckboxPiscina() {
        return checkboxPiscina;
    }

    public JCheckBox getCheckboxSpa() {
        return checkboxSpa;
    }

    public JLabel getLabelCostoTotalAdicionales() {
        return labelCostoTotalAdicionales;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonElegirServiciosAdicionales;
    private javax.swing.JCheckBox checkboxGimnasio;
    private javax.swing.JCheckBox checkboxNinguno;
    private javax.swing.JCheckBox checkboxPiscina;
    private javax.swing.JCheckBox checkboxSpa;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelCostoTotalAdicionales;
    // End of variables declaration//GEN-END:variables
}
